// 100th Anniversary Centenary Edition of Aron Nimzowitsch's My System (1925–2025).
// Completely mapped to interactive book chapters, drills, and master case files.

export const MY_SYSTEM_PARTS = [
  {
    id: 'elements',
    title: 'Part I. The Elements',
    summary: 'The strategic vocabulary: center, open files, 7th & 8th ranks, passed pawns, exchanging, endgame strategy, pins, discovered checks, and pawn chains.',
    chapters: [
      {
        id: 'center',
        number: 'I',
        title: 'The Centre and Development',
        summary: 'Definitions of the 4 central squares, democracy of pieces, pawn moves vs piece moves, and the mortal danger of pawn hunting.',
        lessonId: 'my-system/01-center-and-development',
        status: 'playable',
        estMinutes: 12,
      },
      {
        id: 'open-files',
        number: 'II',
        title: 'The Open File',
        summary: 'How open files arise, why invasion is the sole purpose, overcoming obstructing pawns, and outposts as forward springboards.',
        lessonId: 'my-system/02-open-files',
        status: 'playable',
        estMinutes: 14,
      },
      {
        id: 'seventh-eighth-ranks',
        number: 'III',
        title: 'The 7th and 8th Ranks',
        summary: 'Converging attacks, revolutionary attacks, the infamous doubled "blind pigs", drawing weapons, and turning movements.',
        lessonId: 'my-system/03-seventh-and-eighth-ranks',
        status: 'playable',
        estMinutes: 14,
      },
      {
        id: 'illustrative-games-part-1',
        number: 'III-A',
        title: 'Illustrative Games (Chapters 1–3)',
        summary: 'Master studies: Nimzowitsch vs Alapin (1913) demonstrating rapid central development, open-file control, and bishop trapping.',
        lessonId: 'my-system/04-illustrative-games-part-1',
        status: 'playable',
        estMinutes: 16,
      },
      {
        id: 'passed-pawns',
        number: 'IV',
        title: 'The Passed Pawn',
        summary: 'The candidate pawn, the passed pawn’s "lust to expand", the doctrine of the blockade, and the blockader’s active mission.',
        lessonId: 'my-system/05-passed-pawn',
        status: 'playable',
        estMinutes: 15,
      },
      {
        id: 'exchanging',
        number: 'V',
        title: 'On Exchanging',
        summary: 'Trading with surgical intent: seizing open files, destroying vital defenders, avoiding tempo loss, and simplifying into victory.',
        lessonId: 'my-system/06-exchanging',
        status: 'playable',
        estMinutes: 12,
      },
      {
        id: 'endgame-strategy',
        number: 'VI',
        title: 'Elements of Endgame Strategy',
        summary: 'The awakening and centralization of the King, active rook placement behind passed pawns, and cutting off the enemy king.',
        lessonId: 'my-system/07-elements-of-endgame-strategy',
        status: 'playable',
        estMinutes: 14,
      },
      {
        id: 'pin',
        number: 'VII',
        title: 'The Pinned Piece',
        summary: 'Wholly pinned vs half-pinned pieces, the golden rule of piling up on the pinned target, and practical unpinning techniques.',
        lessonId: 'my-system/08-pinned-piece',
        status: 'playable',
        estMinutes: 13,
      },
      {
        id: 'discovered-checks',
        number: 'VIII',
        title: 'Discovered Check',
        summary: 'The masked battery, unstoppable double checks compelling the king to flee, and the legendary seesaw / windmill.',
        lessonId: 'my-system/09-discovered-check',
        status: 'playable',
        estMinutes: 12,
      },
      {
        id: 'pawn-chain',
        number: 'IX',
        title: 'The Pawn Chain',
        summary: 'The head and the base, the cardinal rule (attack the base!), siege warfare against the base, and the two theatres of war.',
        lessonId: 'my-system/10-pawn-chain',
        status: 'playable',
        estMinutes: 16,
      },
    ],
  },
  {
    id: 'positional-play',
    title: 'Part II. Positional Play',
    summary: 'The elements become a method: prophylaxis, the mysterious rook move, doubled pawn complexes, the Isolani, overprotection, and manoeuvring.',
    chapters: [
      {
        id: 'prophylaxis-and-center',
        number: 'X',
        title: 'Prophylaxis and the Centre',
        summary: 'Anticipating the opponent’s liberating freeing move, suffocating counterplay, and deploying the mysterious rook move.',
        lessonId: 'my-system/11-prophylaxis-and-the-centre',
        status: 'playable',
        estMinutes: 15,
      },
      {
        id: 'doubled-pawn-restraint',
        number: 'XI',
        title: 'The Doubled Pawn and Restraint',
        summary: 'Static vs dynamic weaknesses, the doubled pawn complex, blockading doubled pawns, and restraining majorities.',
        lessonId: 'my-system/12-doubled-pawns-and-restraint',
        status: 'playable',
        estMinutes: 15,
      },
      {
        id: 'isolated-queen-pawn',
        number: 'XII',
        title: "The Isolated Queen's Pawn",
        summary: 'The Isolani: dynamic spatial attacking asset vs endgame liability, blockading the d5 outpost, and handling hanging pawns.',
        lessonId: 'my-system/13-isolated-queen-pawn',
        status: 'playable',
        estMinutes: 15,
      },
      {
        id: 'overprotection',
        number: 'XIII',
        title: 'Overprotection and Weak Pawns',
        summary: 'Systematic surplus defense of decisive points (e5/d4), radiating energy, and gaining elastic freedom for all defending pieces.',
        lessonId: 'my-system/14-overprotection',
        status: 'playable',
        estMinutes: 14,
      },
      {
        id: 'maneuvering',
        number: 'XIV',
        title: 'Manoeuvring Against Weaknesses',
        summary: 'The Principle of Two Weaknesses, shifting pressure across wings, and utilizing central outposts as fluid pivots.',
        lessonId: 'my-system/15-manoeuvring',
        status: 'playable',
        estMinutes: 14,
      },
    ],
  },
  {
    id: 'master-games',
    title: 'Part III. Master Case Files & Revolution',
    summary: 'The crowning masterpieces of hypermodern thought and the historical revolution in chess.',
    chapters: [
      {
        id: 'immortal-zugzwang',
        number: 'XV',
        title: 'The Immortal Zugzwang Game & The Revolution',
        summary: 'Sämisch vs Nimzowitsch (Copenhagen 1923): the immortal masterpiece of total board paralysis and the hypermodern revolution.',
        lessonId: 'my-system/16-immortal-zugzwang-and-revolution',
        status: 'playable',
        estMinutes: 18,
      },
    ],
  },
];

export function flattenMySystemChapters() {
  return MY_SYSTEM_PARTS.flatMap((part) => part.chapters.map((chapter) => ({ ...chapter, part })));
}
